export const settingsCheckboxes = [
  {
    key: 1,
    id: "structuredData",
    name: "structuredData",
    about: "enable structured data",
    label: "Structured Data",
  },
  {
    key: 2,
    id: "androidChromeIcons",
    name: "androidChromeIcons",
    about: "enable androidChromeIcons",
    label: "Android Chrome Icons",
  },
  {
    key: 3,
    id: "msTags",
    name: "msTags",
    about: "enable msTags",
    label: "Microsoft Tags",
  },
  {
    key: 4,
    id: "safariTags",
    name: "safariTags",
    about: "enable safariTags",
    label: "Safari Tags",
  },
  {
    key: 5,
    id: "appleTags",
    name: "appleTags",
    about: "enable appleTags",
    label: "Apple Tags",
  },
  {
    key: 6,
    id: "openGraphTags",
    name: "openGraphTags",
    about: "enable openGraphTags",
    label: "Open Graph Tags",
  },
  {
    key: 7,
    id: "twitterTags",
    name: "twitterTags",
    about: "enable twitterTags",
    label: "Twitter Tags",
  },
  {
    key: 8,
    id: "facebookTags",
    name: "facebookTags",
    about: "enable facebookTags",
    label: "Facebook Tags",
  },
];

export const robotCheckboxes = [
  {
    key: 1,
    id: "allow",
    name: "allow",
    about: "enable allow",
    label: "Allow bots",
  },
  {
    key: 2,
    id: "disallow",
    name: "disallow",
    about: "enable disallow",
    label: "Disallow bots",
  },
  {
    key: 3,
    id: "followLinks",
    name: "followLinks",
    about: "enable followLinks",
    label: "Enable follow links",
  },
  // optional=================
  {
    key: 4,
    id: "noindex",
    name: "noindex",
    about: "enable noindex",
    label: "noindex",
  },
  {
    key: 5,
    id: "nofollow",
    name: "nofollow",
    about: "enable nofollow",
    label: "nofollow",
  },
  {
    key: 6,
    id: "noarchive",
    name: "noarchive",
    about: "enable noarchive",
    label: "noarchive",
  },
  {
    key: 7,
    id: "nosnippet",
    name: "nosnippet",
    about: "enable nosnippet",
    label: "nosnippet",
  },
  {
    key: 8,
    id: "noimageindex",
    name: "noimageindex",
    about: "enable noimageindex",
    label: "noimageindex",
  },
  {
    key: 9,
    id: "unavailable_after",
    name: "unavailable_after",
    about: "enable unavailable_after",
    label: "unavailable_after",
  },

  {
    key: 10,
    id: "sitemap",
    name: "sitemap",
    about: "enable sitemap",
    label: "sitemap",
  },
];

export const projectMetaData = [
  // name(required) , projectUrl(required) , logo,primary color, background color
  {
    key: 1,
    name: "name",
    id: "name",
    type: "text",
    placeholder: "Project Name",
    required: true,
    label: "Name",
  },
  {
    key: 2,
    name: "projectUrl",
    id: "projectUrl",
    type: "url",
    placeholder: "Project URL",
    required: true,
    label: "Project url",
  },
  {
    key: 3,
    name: "logo",
    id: "logo",
    type: "url",
    placeholder: "Project Logo URL",
    required: false,
    label: "Logo",
  },
  {
    key: 4,
    name: "primaryColor",
    id: "primaryColor",
    type: "color",
    placeholder: "Project Primary Color",
    required: false,
    label: "Primary Color",
  },
  {
    key: 5,
    name: "backgroundColor",
    id: "backgroundColor",
    type: "color",
    placeholder: "Project Background Color",
    required: false,
    label: "Background Color",
  },
];

export const pageMetaData = [
  // title (required), description(required), pageUrl (required), image , locale
  {
    key: 1,
    name: "title",
    id: "title",
    type: "text",
    placeholder: "Page Title",
    required: true,
    label: "Title",
  },
  {
    key: 2,
    name: "description",
    id: "description",
    type: "text",
    placeholder: "Page Description",
    required: true,
    label: "Description",
  },
  {
    key: 3,
    name: "pageUrl",
    id: "pageUrl",
    type: "url",
    placeholder: "Page URL",
    required: true,
    label: "Page url",
  },
  {
    key: 4,
    name: "author",
    id: "author",
    type: "text",
    placeholder: "Page Author",
    required: false,
    label: "Author",
  },
  {
    key: 5,
    name: "image",
    id: "image",
    type: "url",
    placeholder: "Page Image URL",
    required: false,
    label: "Image",
  },
  {
    key: 6,
    name: "locale",
    id: "locale",
    type: "text",
    placeholder: "Page Locale",
    required: false,
    label: "Locale",
  },
];
